# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        
      - name: Check test
        run: npm test

  publish-npm:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install

      - name: Build storybook
        run: npm run build-sb

      - name: Set GitHub user details
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
      - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: storybook-static 

      - name: Build packages
        run: npx lerna run build
      
      - name: Version packages
        run: npx lerna version --conventional-commits --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
          
      - name: Publish packages
        run: npx lerna publish from-package --yes --force-publish=*
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
